<?php
$dbName = 'bimbo';

/* load all models */
$this->loadModel('Barang');
$this->loadModel('BayarBon');
$this->loadModel('DBon');
$this->loadModel('Diskon');
$this->loadModel('DNotaBawa');
$this->loadModel('DNotaRetur');
$this->loadModel('DNotaTunai');
$this->loadModel('DOrder');
$this->loadModel('DPembelian');
$this->loadModel('DRencanaBeli');
$this->loadModel('DReturBeli');
$this->loadModel('DStockOpname');
$this->loadModel('DTransfer');
$this->loadModel('DTransferKembali');
$this->loadModel('Komisi');
$this->loadModel('Lokasi');
$this->loadModel('LokasiBarang');
$this->loadModel('MBon');
$this->loadModel('MNotaBawa');
$this->loadModel('MNotaRetur');
$this->loadModel('MNotaTunai');
$this->loadModel('MOrder');
$this->loadModel('MPembelian');
$this->loadModel('MRencanaBeli');
$this->loadModel('MReturBeli');
$this->loadModel('MStockOpname');
$this->loadModel('MTransfer');
$this->loadModel('MTransferKembali');
$this->loadModel('NoBarang');
$this->loadModel('Pelanggan');
$this->loadModel('ReturBonLama');
$this->loadModel('Setup');
$this->loadModel('Setuppromo');
$this->loadModel('Tempak7');
$this->loadModel('Tempak7rinci');
?>